
us_state_capitals = {
    "Alabama": "Montgomery",
    "Alaska": "Juneau",
    "Arizona": "Phoenix",
    "Arkansas": "Little Rock",
    "California": "Sacramento",
    "Colorado": "Denver",
    "Connecticut": "Hartford",
    "Delaware": "Dover",
    "Florida": "Tallahassee",
    "Georgia": "Atlanta",
    "Hawaii": "Honolulu",
    "Idaho": "Boise",
    "Illinois": "Springfield",
    "Indiana": "Indianapolis",
    "Iowa": "Des Moines",
    "Kansas": "Topeka",
    "Kentucky": "Frankfort",
    "Louisiana": "Baton Rouge",
    "Maine": "Augusta",
    "Maryland": "Annapolis",
    "Massachusetts": "Boston",
    "Michigan": "Lansing",
    "Minnesota": "Saint Paul",
    "Mississippi": "Jackson",
    "Missouri": "Jefferson City",
    "Montana": "Helena",
    "Nebraska": "Lincoln",
    "Nevada": "Carson City",
    "New Hampshire": "Concord",
    "New Jersey": "Trenton",
    "New Mexico": "Santa Fe",
    "New York": "Albany",
    "North Carolina": "Raleigh",
    "North Dakota": "Bismarck",
    "Ohio": "Columbus",
    "Oklahoma": "Oklahoma City",
    "Oregon": "Salem",
    "Pennsylvania": "Harrisburg",
    "Rhode Island": "Providence",
    "South Carolina": "Columbia",
    "South Dakota": "Pierre",
    "Tennessee": "Nashville",
    "Texas": "Austin",
    "Utah": "Salt Lake City",
    "Vermont": "Montpelier",
    "Virginia": "Richmond",
    "Washington": "Olympia",
    "West Virginia": "Charleston",
    "Wisconsin": "Madison",
    "Wyoming": "Cheyenne"
}

us_states_info = {
    "Alabama": {"abb": "AL", "capital": "Montgomery", "timezone": "CST", "pop": 5024279},
    "Alaska": {"abb": "AK", "capital": "Juneau", "timezone": "AKST", "pop": 733391},
    "Arizona": {"abb": "AZ", "capital": "Phoenix", "timezone": "MST", "pop": 7151502},
    "Arkansas": {"abb": "AR", "capital": "Little Rock", "timezone": "CST", "pop": 3011524},
    "California": {"abb": "CA", "capital": "Sacramento", "timezone": "PST", "pop": 39538223},
    "Colorado": {"abb": "CO", "capital": "Denver", "timezone": "MST", "pop": 5773714},
    "Connecticut": {"abb": "CT", "capital": "Hartford", "timezone": "EST", "pop": 3605944},
    "Delaware": {"abb": "DE", "capital": "Dover", "timezone": "EST", "pop": 989948},
    "Florida": {"abb": "FL", "capital": "Tallahassee", "timezone": "EST", "pop": 21538187},
    "Georgia": {"abb": "GA", "capital": "Atlanta", "timezone": "EST", "pop": 10711908},
    "Hawaii": {"abb": "HI", "capital": "Honolulu", "timezone": "HST", "pop": 1455271},
    "Idaho": {"abb": "ID", "capital": "Boise", "timezone": "MST", "pop": 1839106},
    "Illinois": {"abb": "IL", "capital": "Springfield", "timezone": "CST", "pop": 12812508},
    "Indiana": {"abb": "IN", "capital": "Indianapolis", "timezone": "EST", "pop": 6785528},
    "Iowa": {"abb": "IA", "capital": "Des Moines", "timezone": "CST", "pop": 3190369},
    "Kansas": {"abb": "KS", "capital": "Topeka", "timezone": "CST", "pop": 2937880},
    "Kentucky": {"abb": "KY", "capital": "Frankfort", "timezone": "EST", "pop": 4505836},
    "Louisiana": {"abb": "LA", "capital": "Baton Rouge", "timezone": "CST", "pop": 4657757},
    "Maine": {"abb": "ME", "capital": "Augusta", "timezone": "EST", "pop": 1362359},
    "Maryland": {"abb": "MD", "capital": "Annapolis", "timezone": "EST", "pop": 6177224},
    "Massachusetts": {"abb": "MA", "capital": "Boston", "timezone": "EST", "pop": 7029917},
    "Michigan": {"abb": "MI", "capital": "Lansing", "timezone": "EST", "pop": 10077331},
    "Minnesota": {"abb": "MN", "capital": "Saint Paul", "timezone": "CST", "pop": 5706494},
    "Mississippi": {"abb": "MS", "capital": "Jackson", "timezone": "CST", "pop": 2961279},
    "Missouri": {"abb": "MO", "capital": "Jefferson City", "timezone": "CST", "pop": 6154913},
    "Montana": {"abb": "MT", "capital": "Helena", "timezone": "MST", "pop": 1084225},
    "Nebraska": {"abb": "NE", "capital": "Lincoln", "timezone": "CST", "pop": 1961504},
    "Nevada": {"abb": "NV", "capital": "Carson City", "timezone": "PST", "pop": 3104614},
    "New Hampshire": {"abb": "NH", "capital": "Concord", "timezone": "EST", "pop": 1377529},
    "New Jersey": {"abb": "NJ", "capital": "Trenton", "timezone": "EST", "pop": 9288994},
    "New Mexico": {"abb": "NM", "capital": "Santa Fe", "timezone": "MST", "pop": 2117522},
    "New York": {"abb": "NY", "capital": "Albany", "timezone": "EST", "pop": 20201249},
    "North Carolina": {"abb": "NC", "capital": "Raleigh", "timezone": "EST", "pop": 10439388},
    "North Dakota": {"abb": "ND", "capital": "Bismarck", "timezone": "CST", "pop": 779094},
    "Ohio": {"abb": "OH", "capital": "Columbus", "timezone": "EST", "pop": 11799448},
    "Oklahoma": {"abb": "OK", "capital": "Oklahoma City", "timezone": "CST", "pop": 3959353},
    "Oregon": {"abb": "OR", "capital": "Salem", "timezone": "PST", "pop": 4237256},
    "Pennsylvania": {"abb": "PA", "capital": "Harrisburg", "timezone": "EST", "pop": 13002700},
    "Rhode Island": {"abb": "RI", "capital": "Providence", "timezone": "EST", "pop": 1097379},
    "South Carolina": {"abb": "SC", "capital": "Columbia", "timezone": "EST", "pop": 5118425},
    "South Dakota": {"abb": "SD", "capital": "Pierre", "timezone": "CST", "pop": 886667},
    "Tennessee": {"abb": "TN", "capital": "Nashville", "timezone": "CST", "pop": 6910840},
    "Texas": {"abb": "TX", "capital": "Austin", "timezone": "CST", "pop": 29145505},
    "Utah": {"abb": "UT", "capital": "Salt Lake City", "timezone": "MST", "pop": 3271616},
    "Vermont": {"abb": "VT", "capital": "Montpelier", "timezone": "EST", "pop": 643077},
    "Virginia": {"abb": "VA", "capital": "Richmond", "timezone": "EST", "pop": 8631393},
    "Washington": {"abb": "WA", "capital": "Olympia", "timezone": "PST", "pop": 7693612},
    "West Virginia": {"abb": "WV", "capital": "Charleston", "timezone": "EST", "pop": 1793716},
    "Wisconsin": {"abb": "WI", "capital": "Madison", "timezone": "CST", "pop": 5893718},
    "Wyoming": {"abb": "WY", "capital": "Cheyenne", "timezone": "MST", "pop": 576851}
}

